models_dir: "/Users/maximbragilovski/model_evalution/artifacts/parkWise/ucd_10"
guidelines_dir: "/Users/maximbragilovski/model_evalution/artifacts/agentB_best_guidelines.json"
aggregate_dir: "/Users/maximbragilovski/model_evalution/artifacts/vizualize"
